### ISSUE TITLE
`equal` wrong when destructuring value within `equal` function

### ISSUE THREAD

**Issue by victorlearned** [Sullux/fp-light#32]
Looks like this use to work in fp `1.1.6` but doesn't seem to when testing against `1.1.7` and above

```javascript
   // USE to work
    test('should equal', () => {
      const extra = { test: 1, foo: true, bar: false}
      const justEnough = { foo: true, bar: false}
      const output = pipe(
        equal(({ extra: { test, ...rest } }) => rest, _.justEnough)
      )({
        extra,
        justEnough,
      });
      expect(output).toEqual(true)
    })

```

This works though:

```javascript

    test('should equal with resolve ahead of time', () => {
      const extra = { test: 1, foo: true, bar: false}
      const justEnough = { foo: true, bar: false}
      const output = pipe(
        [({ extra: { test, ...rest } }) => rest, _.justEnough],
        equal(_[0],_[1])
      )({
        extra,
        justEnough,
      });
      expect(output).toEqual(true)
    })
```

**Comment by Sullux** [comment]
Interesting. I dug into this a bit and this looks like a direct side-effect of what's causing #30. I will update as I learn more...

**Comment by Sullux** [comment]
Ok, I was wrong about this one. This is yet another side effect of the mutation I introduced to fix the performance problems in `reduce` and other mapping functions. I have now fully changed this over to the non-mutating (cache-based) version of the performance fix and that has eliminated this bug.

See [the PR](https://github.com/Sullux/fp-light/pull/33) for details. Install v 1.2.32 to get this fix.
